# Site wide configuration

title:            CESTA Fellows
locale:           en_US
url: http://cestastanford.github.io/fellows/


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: CESTA
  fullname: Center for Spatial and Textual Analysis
  org: Stanford University
  avatar: CESTA_logo.png
  bio: "The Center for Spatial and Textual Analysis at Stanford University."
  email: cesta@stanford.edu
  twitter: cesta_stanford

  github: cestastanford


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
